### ISSUE TITLE
Add move semantics to objects and consider their nullability

### ISSUE THREAD

**Issue by janekb04** [janekb04/glfwpp#16]
Currently the objects are non-copyable, but also non-movable. This limits their usage. They can stay non copyable like in GLFW, but they should be movable as they are merely GLFW object owners. As they can also be constructed from GLFW object handles, which can be `NULL` perhaps an `isNull()` method should be added to test if the object has been moved-from and/or constructed from a null GLFW handle. Otherwise the construction from a null GLFW handle should be prohibited by throwing an exception in the converting constructor. Assert should be added in methods to check that the object is non-null.

**Comment by CarloWood** [comment]
Hi Janek, I was going to raise this issue next - heheh, but then found this Issue.

I want to store multiple Windows (ie, the user runs an application while that is already running. In that case dbus is used to make the already running application open a new window). I was/am wondering if `class Window` can be stored safely in a `std::vector`. That not just requires it to be movable, but also that the library isn't storing any pointers to it anywhere.

Is there a mailinglist where I can ask such questions? Or can I contact your directly? Github doesn't seem to allow me to do so.

**Comment by CarloWood** [comment]
I just found:

```
        //Takes ownership
        explicit Window(GLFWwindow* handle_) :
            _handle{handle_},
            _userPtr{nullptr}
        {   
            _setPointerFromHandle(_handle, this);
```

where

```
        static void _setPointerFromHandle(GLFWwindow* handle_, Window* ptr_)
        {
            glfwSetWindowUserPointer(handle_, ptr_);
        }
```

So, a pointer to each `Window` instance is most definitely stored, and they are therefore no movable.

That makes the current code correct no? (Not copyable nor movable).

**Comment by janekb04** [comment]
@CarloWood

Hi,

I saw all your contributions to GLFWPP and I’m really glad to see someone be so interested in the library. Thanks for all your current and future contributions.
I am currently away and won’t have the chance to work on GLFWPP until next week, however at glance I agree with most of your suggestions.

Regarding your question on how we may communicate, we can either use email (`janekb04 at iCloud`) or, if you’d be comfortable with that, a service such as Messenger, Signal or Discord.

Best,
Janek

_I originally sent this message to the email address in your profile, however the server `alinoe.com` doesn't seem to respond, so I'm sending it here too._

**Comment by CarloWood** [comment]
And not just somebody 🥇 Haha. I have one 23" monitor dedicated to chat (although occasionally guilty of burying all those windows under a terminal). Using that for among which IRC and discord (different social circles per service). If you aren't on IRC, which I use for coding (CarloWood on libera.chat), then I guess it will be discord. I use a lot of pseudonyms though, and CW is an IRC thing, but if you won't tell anyone then I can tell you who I am on discord ;). Lemme know where.

**Comment by CarloWood** [comment]
Are you still alive?

**Comment by janekb04** [comment]
Yes, but busy. GLFWPP is not my top priority at the moment. I will get in touch when I will have time.
