### ISSUE TITLE
Fails initialization with vulkan

### ISSUE THREAD

**Issue by Golgovskiy** [janekb04/glfwpp#270]
Using Vulkan API (glfwWindowHint(GLFW_CLIENT_API, GLFW_NO_API)).

`Assertion failed: errorCode_ != GLFW_NOT_INITIALIZED, file D:\Repositories\Engine\glfwpp\include\glfwpp\glfwpp.h, line 24`

Using glfw::init() does not initialise the glfw. Standart glfwInit() works thou. 
Using glfw::init after glfwInit() changes nothing, but using glfw::init() first has no error. I am concerned whether i need to call glfwTerminate() thou. Trying to store GlfwLibrary in a smart pointer causes error after window is closed.
I suspect it might be GlfwLibrary dying before window is initialized...

**Comment by janekb04** [comment]
Hi, `glfw::init` returns an object of type `GlfwLibrary`. That object `terminate`s GLFW on destruction, so you have to store it somewhere. You cannot really store it in a smart pointer because I didn't think of moving it anywhere. You'll probably have to store it inside a `struct` or a `tuple` and store that in a smart pointer. I haven't tested it, but I think that this should work:
```cpp
// Aggregate type
struct holder {
    glfw::GlfwLibrary lib;
};
auto GLFW = std::make_unique<holder>(glfw::init());
```
You'll have to make sure that this object outlives all glfw objects and commands.

I admit that this wasn't the best design choice on my part, and I am planning to revise this and other parts of the library's interface.

**Comment by Golgovskiy** [comment]
It's just as I thought, but I tried putting init into a main() function before, hoping it stay in scope until the end of program. However it didn't have any effect. 
Maybe storing it was removed by compiler since I didn't use it anywhere later. 
And yes, I noted the storing of object in example and nodiscard inside.
What is different about not using vulkan thou? Why does it work?

**Comment by janekb04** [comment]
Using Vulkan shouldn’t have any effect. Could you send your `main` function, or at least it’s relevant parts?

**Comment by Golgovskiy** [comment]
```
   
        glfw::init();

        glfw::WindowHints{
            .clientApi = glfw::ClientApi::None,
        }.apply();

        window = glfw::Window(WIDTH, HEIGHT, "Vulkan", nullptr, nullptr);

        ...
        // load of vulkan stuff here
        ...

        while (!window->shouldClose()) {
            glfw::pollEvents();
        }
```

**Comment by janekb04** [comment]
The problem with this code is that the `GlfwLibrary` isn’t stored anywhere. It gets destructed immediately after the call to `glfw::init`. You have to assign the result of `init` to a variable.
```
int main() {
       auto GLFW = glfw::init();

       glfw::WindowHints{
           .clientApi = glfw::ClientApi::None,
       }.apply();

       window = glfw::Window(WIDTH, HEIGHT, "Vulkan", nullptr, nullptr);

       ...
       // load of vulkan stuff here
       ...

       while (!window->shouldClose()) {
           glfw::pollEvents();
       }
}
```

**Comment by Golgovskiy** [comment]
Oh, sorry. I actually stored the thing like you shown after previous comments.
Now it opens the window, but assertion error pops up anyway after it's closed.

P.S. I've just discovered that this problem lies in try catch block. I took it out of it and now it works properly.

Okay, i think my issue is fixed. Many thanks. Would love to find a way to actually put it inside the exception catcher thou.

**Comment by janekb04** [comment]
It just came to my mind that there is an obscure trick you could use to declare in the exception block. You could allocate the library object using a shared pointer. Then, you would throw a custom exception that would internally store that same shared pointer. This would ensure that the library doesn’t get terminated until the catch block completes.
This is convoluted, and personally I’d just wrap the try catch block with a second try catch block. The key thing is to make the scope of the library object extend past the window.
